version: "3.8"
services: 
  norah-thesis:
    container_name: norah-thesis
    build:
      context: .
      args:
        - JULIA_VERSION=1.7.2
    ports: 
      - "2019:2019"
    volumes: 
      - .:/home/julia/project
